from dydx3.constants import API_HOST_GOERLI, API_HOST_MAINNET
from decouple import config

# SELECT MODE
MODE = "DEVELOPMENT"

# Close all open positions and orders
ABORT_ALL_POSITIONS = True

# Find Cointegrated Pairs
FIND_COINTEGRATED = True

# Place Trades
PLACE_TRADES = True

# Resolution
RESOLUTION = "1HOUR"

# Stats Window
WINDOW = 21

# Thresholds - Opening
MAX_HALF_LIFE = 24
ZSCORE_THRESH = 1.5
USD_PER_TRADE = 50
USD_MIN_COLLATERAL = 1880

# Thresholds - Opening
CLOSE_AT_ZSCORE_CROSS = True

# Keys Testnet
ETHEREUM_ADDRESS = config("ETHEREUM_ADDRESS")
STARK_PRIVATE_KEY_TESTNET = config("STARK_PRIVATE_KEY_TESTNET")
DYDX_API_KEY_TESTNET = config("DYDX_API_KEY_TESTNET")
DYDX_API_SECRET_TESTNET = config("DYDX_API_SECRET_TESTNET")
DYDX_API_PASSPHRASE_TESTNET = config("DYDX_API_PASSPHRASE_TESTNET")

# KETS - EXPORT
STARK_PRIVATE_KEY = STARK_PRIVATE_KEY_TESTNET if MODE == "DEVELOPMENT" else ""
DYDX_API_KEY = DYDX_API_KEY_TESTNET if MODE == "DEVELOPMENT"  else ""
DYDX_API_SECRET = DYDX_API_SECRET_TESTNET if MODE == "DEVELOPMENT" else ""
DYDX_API_PASSPHRASE = DYDX_API_PASSPHRASE_TESTNET if MODE == "DEVELOPMENT" else ""

# HOST - EXPORT
HOST = API_HOST_GOERLI if MODE == "DEVELOPMENT" else API_HOST_MAINNET

# HTTP Provide
HTTP_PROVIDER_TESTNET = config("HTTP_PROVIDER_TESTNET")
HTTP_PROVIDER = HTTP_PROVIDER_TESTNET if MODE == "DEVELOPMENT" else ""

